In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
a.ndim

1

In [5]:
a.shape

(3,)

In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
b.shape #Rows,Columns

(2, 3)

In [12]:
b[1][2]

4.0